### ISSUE TITLE
Allow configuration of Container Security Context in Helm chart

### ISSUE THREAD

**Issue by djessich** [minio/operator#1366]
**Is your feature request related to a problem? Please describe.**
I cannot set the security context for the created containers. It is only allowed to set the security context of the created pods.

**Describe the solution you'd like**
Please implement security context configuration for the created containers additionally to the security context of the created pods.

**Describe alternatives you've considered**
Currently there are no alternatives available.

**Additional Information**
It should be allowed to set the security context for the created containers to prevent privilege escalation and to configure read only root filesystem. Both options are a Kubernetes Security best practice.

**Comment by dvaldivia** [comment]
This is a controversial one since adding support for this makes the minimal version of Kubernetes to be `1.22` I believe since that's when Container Security Context was added, with the release of kubernetes `1.26` we are now only supporting down to `1.21` so when `1.22` is our floor we will add support for Container Security Context. 

Unless we find a backwards compatible approach to add this, we cannot add it, but we will look into it.

**Comment by allanrogerr** [comment]
Fixed in https://github.com/minio/operator/pull/1372. Please see for comments.

**Comment by dilverse** [comment]
PR #1372 fixes this issue, feel free to try it out. Closing this issue
