### ISSUE TITLE
`kubectl minio tenant create --output`'s YAML is invalid

### ISSUE THREAD

**Issue by clovis-dugue** [minio/operator#1388]
## Expected Behavior

Using `kubectl minio tenant create test --namespace test --servers 1 --volumes 1 --capacity 100 --output` should create a valid Tenant configuration that can be `kubectl apply`ed (values for syntax purposes only)

## Current Behavior

When trying to use `kubectl-minio --output` to create a basic tenant's YAML, then `kubectl apply` to create the tenant, the CRD is not validated due to extra properties being generated by `kubectl-minio` 
```txt
Error from server (BadRequest): error when creating "test": Tenant in version "v2" cannot be handled as a Tenant: strict decoding error: unknown field "spec.log.db.volumeClaimTemplate.metadata.creationTimestamp", unknown field "spec.pools[0].volumeClaimTemplate.metadata.creationTimestamp"
```

## Possible Solution

Do not generate any `creationTimestamp`s when creating the YAML template, as these are values that should be set only once applied to the server. Having those keys at `null` and applying them creates unreliable parsing situations.  
My current workaround is to run 
```sh
yq -i "del(.spec.log.db.volumeClaimTemplate.metadata.creationTimestamp)" tenant.yaml
yq -i "del(.spec.pools[0].volumeClaimTemplate.metadata.creationTimestamp)" tenant.yaml
```

## Steps to Reproduce (for bugs)

Assuming a cluster with a valid Operator is available and configured with the default behavior from `kubectl minio init`:
```sh
kubectl minio tenant create test --namespace test --servers 1 --volumes 1 --capacity 100 --output > bug.yaml
kubectl apply bug.yaml
```

## Context

I encountered this issue while trying to create a tenant in an automated way

## Regression

Unknown

## Your Environment

* Version used (`minio-operator`): 4.5.6
* Environment name and version (e.g. kubernetes v1.17.2): 
```txt
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.0", GitCommit:"b46a3f887ca979b1a5d14fd39cb1af43e7e5d12d", GitTreeState:"clean", BuildDate:"2022-12-08T19:58:30Z", GoVersion:"go1.19.4", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.4", GitCommit:"872a965c6c6526caa949f0c6ac028ef7aff3fb78", GitTreeState:"clean", BuildDate:"2022-11-09T13:29:58Z", GoVersion:"go1.19.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by D1StrX** [comment]
Using kubectl minio version v4.5.8, kubernetes 1.26.1 I see the operator logs also spammed with `1 warnings.go:70] unknown field "spec.pools[0].volumeClaimTemplate.metadata.creationTimestamp"`

**Comment by pjuarezd** [comment]
## Finding the root cause
The problem is with the field `spec.pools[*].volumeClaimTemplate`. This Object is of type `*corev1.PersistentVolumeClaim`, we [set the value of the fields](https://github.com/minio/operator/blob/757a88cf5ef2c9d8cd103b41f4cd692df8d6821b/kubectl-minio/cmd/resources/common.go#L65-L67) `Kind` and `APIVersion` , because of that the struct `metav1.TypeMeta` is initialized.

Unlucky for us 2 encoding problems happen with the `metav1.TypeMeta` structure, and 1 code-gen, that all together create the race condition:

1) When an object of type `metav1.TypeMeta` is `yaml.Marshal()`, the yaml package doesn't know how to handle the `creationTimestamp` field  and sets "null" instead of not rendering it at all, that is why when executing this command  `kubectl minio tenant create test --namespace test --servers 1 --volumes 1 --capacity 100 --output` the output includes the `creationTimestamp=null` assigned field.
See this Kubernetes issue for a clear example https://github.com/kubernetes/apimachinery/issues/119

2) When usign the Tenant go structure, we invoke the  `Created`method, like in the example below, at some point k8s apimachinery handles the "Zero"value of the `creationTimestamp` field as null value and assigns this value to the field, this seems to be the culprit when using Tenant CRD, which them all: Console UI, helm Chart and straight yaml in `kubectl apply -f tenant.yaml` command, eventually operator handles the creation of the resources adding the timestamp field, creating the field `creationTimestamp ` with null value.

https://github.com/kubernetes/apimachinery/commit/6556ef5891e14b543b3e255048a7647e70785f7f
https://github.com/kubernetes/apimachinery/blob/57f2a0733447cfd41294477d833cce6580faaca3/pkg/apis/meta/v1/time.go#L142-L145

 ```go
 operatorClient.MinioV2().Tenants(tenant.Namespace).Create(context.Background(), tenant, v1.CreateOptions{})
```

3) Finally, the Tenant CRD is created using the `sigs.k8s.io/controller-tools/cmd/controller-gen`  tool
https://github.com/minio/operator/blob/757a88cf5ef2c9d8cd103b41f4cd692df8d6821b/Makefile#L68
```sh
@${GOPATH}/bin/controller-gen crd:maxDescLen=0,generateEmbeddedObjectMeta=true paths="./..." output:crd:artifacts:config=$(KUSTOMIZE_CRDS)
```

this code generator tool do not include the definition of the `creationTimestamp` field in the tenant CRD under the field `spec.pools[*].volumeClaimTemplate.metadata`, with no option to allow include it.


In conclusion, we end up with a `creationTimestamp=null` assigned field we didn't ask for,  don't want, and we cannot define it.

## Possible Solutions

* Fix K8s API machinery?,  Fix controller-gen to include this field too? This two have been out in the k8s sigs for some years with back and forth conversations around it.

* Stop using the object of type `*corev1.PersistentVolumeClaim`  in the `spec.pools[*].volumeClaimTemplate`, create a clon or somenthing simpler that do not includes a field of type `metav1.TypeMeta`. This will solve the problem with this field, however it could reappear if we introduce another field in the future that inherits that `metav1.TypeMeta` structure.

* Other[ suggested solution](https://github.com/kubernetes/kubernetes/issues/109427#issuecomment-1335676628) is to refactor the Minio Operator Controller to use the `applyconfiguration` approach, which will allways handle the Tenant go struct trough the k8s api machinery more "properly"?. I am starting to experiment with this approach in this PR https://github.com/minio/operator/pull/1470, but I expect it to be a slow process, also the update in `code-generator` is relativelly young, beng berged a couple weeks ago in the `v0.27.0-alpha-2` release, it could take some time to get it to a stable phase  https://github.com/kubernetes/code-generator/commit/9b95cfe8299d1b247a0e9912babdda054213d47b


I just wanted to trhow an update of the research so far, we are looking at it, as soon as a viable way to fix it is found we will work it out.

**Comment by pjuarezd** [comment]
In the short term, a workaround can be to add the `creationTimestamp` in the Tenant CRD definition, to stop receiving the spamming message:

<img width="636" alt="Screenshot 2023-02-27 at 11 50 39 PM" src="https://user-images.githubusercontent.com/1334362/221788174-7c1164a1-03c0-42a0-8556-df7113f2e7aa.png">

**Comment by D1StrX** [comment]
@pjuarezd Thanks for the explanation, I guess/see the option you worked on works out? Looking at the PR

**Comment by pjuarezd** [comment]
I don't think it's solved yet, it's just a step closer @D1StrX, will keep this open as reminder, as soon as we have some bandwith will work in execute the `applyconfiguration` way in the PervistentVolumeClaims instead of the `Create` method, but most likely is going to need a lot of refactors not just the PVC creation.

**Comment by richardzuidhof** [comment]
As a workaround I delete all creationTimestamps from the yaml file.
yq -i 'del(.. | select(has("creationTimestamp")).creationTimestamp)' miniotenant.yml
