### ISSUE TITLE
can't set Raw Capacity

### ISSUE THREAD

**Issue by zlwzlwzlw** [minio/operator#1572]
i set Total Size 25G and start 
<img width="732" alt="1681887005703" src="https://user-images.githubusercontent.com/33961256/232990045-fd097fe1-38e4-4d17-b74c-8a470d5afe87.png">

it's can't limit Raw Capacity and can put object more than 25G,  Usable Capacity is n/a and Internal: n/a

## Your Environment

* Version used (`minio-operator : 5.0.3`):
* Environment name and version (e.g. kubernetes v1.23.15):
* Server type and version:
* Operating System and version (`Linux node-212 3.10.0-957.el7.x86_64 #1 SMP Thu Nov 8 23:39:32 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`):
* Link to your deployment file:

**Comment by shtripat** [comment]
What is storage class used while creation of the tenant?

**Comment by cniackz** [comment]
Can you tell us more about your deployment?

1. Are you using `DirectPV`? If not then what provisioner is being used?.
2. How many MinIO Pods are you having? Are they single pool or do you have multiple pools?
3. Please share the tenant Spec with us

Generally speaking, raw capacity is the limit of total data you can have at a given point.
But since we are using erasure code, then some of that space will be used for parity data.
You can use our calculator to see actually how much space will be free for you to use:

[minio calculator](https://min.io/product/erasure-code-calculator?utm_source=google&utm_medium=cpc&utm_campaign=erasure-code-cpc-040623&utm_term=minio%20calculator&utm_campaign=Erasure+Coding+1.4&utm_source=adwords&utm_medium=ppc&hsa_acc=8976569894&hsa_cam=13884673572&hsa_grp=127699937027&hsa_ad=533469681242&hsa_src=g&hsa_tgt=kwd-2089546985253&hsa_kw=minio%20calculator&hsa_mt=b&hsa_net=adwords&hsa_ver=3&gclid=Cj0KCQjwrfymBhCTARIsADXTablRsiYDgb6rDNA3qNBeaYZa6b2deXV4M2h4W29xdIVHBWlqOdYqfUIaAthcEALw_wcB)

**Comment by cniackz** [comment]
In a real cluster using directpv, this is not possible, just tested:

```sh
root@ubuntu:/# 
root@ubuntu:/# 
root@ubuntu:/# 
root@ubuntu:/# 
root@ubuntu:/# mc admin info myminio --json | jq . | grep -i availspace | cut -d':' -f2- | sed -e "s/,$//" | numfmt --to=iec-i --suffix=B --format="%9.2f"
1023.93MiB
1023.93MiB
1023.93MiB
1023.93MiB
1023.93MiB
1023.93MiB
1023.93MiB
1023.93MiB
1023.93MiB
1023.93MiB
1023.93MiB
1023.93MiB
1023.93MiB
1023.93MiB
1023.93MiB
1023.93MiB
root@ubuntu:/# mc mb myminio/celis
Bucket created successfully `myminio/celis`.
root@ubuntu:/# truncate -s 10G ostechnix.txt
root@ubuntu:/# mc cp ostechnix.txt myminio/celis
/ostechnix.txt:                         10.00 GiB / 10.00 GiB ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 452.82 MiB/s 22sroot@ubuntu:/# mc admin info myminio --json | jq . | grep -i availspace | cut -d':' -f2- | sed -e "s/,$//" | numfmt --to=iec-i --suffix=B --format="%9.2f"
168.87MiB
168.87MiB
168.87MiB
168.87MiB
168.87MiB
168.87MiB
168.87MiB
168.87MiB
168.87MiB
168.87MiB
168.87MiB
168.87MiB
168.87MiB
168.87MiB
168.87MiB
168.87MiB
root@ubuntu:/# mc mb myminio/luis
Bucket created successfully `myminio/luis`.
root@ubuntu:/# mc cp ostechnix.txt myminio/luis
mc: <ERROR> Failed to copy `/ostechnix.txt`. Resource requested is unwritable, please reduce your request rate
root@ubuntu:/# 
root@ubuntu:/# mc admin info myminio --json | jq . | grep -i availspace | cut -d':' -f2- | sed -e "s/,$//" | numfmt --to=iec-i --suffix=B --format="%9.2f"
 12.00KiB
 12.00KiB
 12.00KiB
 12.00KiB
 12.00KiB
 12.00KiB
 12.00KiB
 12.00KiB
 12.00KiB
 12.00KiB
 12.00KiB
 12.00KiB
 12.00KiB
 12.00KiB
 12.00KiB
 12.00KiB
root@ubuntu:/# 
```

When you have no more space available you will get:

```sh
root@ubuntu:/# mc cp ostechnix.txt myminio/luis
mc: <ERROR> Failed to copy `/ostechnix.txt`. Resource requested is unwritable, please reduce your request rate
```

Meaning you ran out of space:

```sh
root@ubuntu:/# mc admin info myminio --json | jq . | grep -i availspace | cut -d':' -f2- | sed -e "s/,$//" | numfmt --to=iec-i --suffix=B --format="%9.2f"
 12.00KiB
 12.00KiB
 12.00KiB
 12.00KiB
 12.00KiB
 12.00KiB
 12.00KiB
 12.00KiB
 12.00KiB
 12.00KiB
 12.00KiB
 12.00KiB
 12.00KiB
 12.00KiB
 12.00KiB
 12.00KiB
root@ubuntu:/# 
```

You can use this command to check on your actual available space per disk, in cofig above I had 16 volumes of 1G each but after trying to put two objects of 10G I ran out of space and putting something beyond that is not possible. So closing this and if this is kind cluster then that is different because we don't actually control the space in that testing environment the same way we do with real cluster + directpv.

Please if this is an issue, provide more details next time like the storage class.

Thank you anyway for opening this issue in our repo!
