### ISSUE TITLE
Minio Operator Path Prefix Change

### ISSUE THREAD

**Issue by jyousefpour1** [minio/operator#1962]
**Is your feature request related to a problem? Please describe.**
Minio Operator helm chart does not allow changing the path prefix of the console ui to something different than /login  in the values.yaml when connected to a reverse proxy
**Describe the solution you'd like**
values.yaml allow a new variable to change path prefix of the minio-operator dashboard

**Describe alternatives you've considered**
Have considered setting the MINIO_SERVER_URL but it defaults to minio-dashboard with any prefix supplied after /

**Additional context**

**Comment by YuriyKrasilnikov** [comment]
@jyousefpour1 After small investigating the problem, I have identified the root cause and a potential solution.

The issue stems from the presence of the <base href="/" /> tag in the operator/web-app/public/index.html file. This tag forces all relative links and resource paths within the web application to be resolved from the site root /, instead of the path prefix where the Minio Operator is deployed when running behind a reverse proxy.

**Comment by ramondeklein** [comment]
MinIO operator UI will be [removed](https://github.com/minio/operator/pull/2205) from v6. Operators are commonly used to manage deployments via Kubernetes resources and are not typically used via a UI. It's not common for operators to have a web interface and it requires a lot of resources to bring all operator features to the web interface. The UI has been lagging behind for a while, so we finally decided to remove it.
