### ISSUE TITLE
Alternative to Operator console

### ISSUE THREAD

**Issue by manju-rn** [minio/operator#2360]
Now that from 6.0 operator is deprecated, is there a way to see all the tenants in the single pane?
The operator console used to help summary all the tenants and easy way of navigating to each of the tenants. Dunno why it is discontinued

**Comment by ramondeklein** [comment]
You can run the following command to show all tenants:
```sh
kubectl get tenant --all-namespaces
```

The most important reason why the console was removed from operator was that it wasn't used that much. Keeping the console up-to-date with the operator features was getting low priority, so the console was lagging behind with features. Even worse... Some operator changes caused bugs in the console that weren't fixed.

Removing the HTTP server from the operator also reduces the memory footprint and attack-surface of the operator. The operator typically runs with elevated privileges in the cluster, so not having an HTTP server is more secure. Although we are not aware of any security issues and this wasn't a reason to remove the console, it was a nice "bonus".

Maintaining the operator console requires significant development resources. Not only because of our changes to the operator, but the world of web frameworks is also changing rapidly. Newer versions of React/Redux also require significant amount of work to keep the console up-to-date. The same with Go and Go packages (although this is often a bit less intrusive). Not updating packages may introduce security issues, so that wasn't an option.

It was either invest in operator console or remove it. Because there is low demand for operator console (although we know some people use it), we decided the drop the operator console. That freed up resources to work on other things that we considered to be more valuable.
