### ISSUE TITLE
documentation is outdated

### ISSUE THREAD

**Issue by Nilegfx** [minio/operator#415]
## Expected Behavior

Documentation (specifically the examples) are easier to follow with simple steps using the latest operator version
## Current Behavior

Documentation causes more confusion than clarity it provides, as an example, the API definition changes from one operator version to another from `pools` to `zones`
creating a tenant with automatic cert doesn't work, the tenant state stuck with `Waiting for MinIO TLS Certificate`

## Possible Solution

update and map the latest docs to the latest operator

## Steps to Reproduce (for bugs)

1. use minikube to create a cluster
2. try to follow the docs by running
```
kubectl minio tenant create minio-tenant-1 \
      --servers 4                             \
      --volumes 16                            \
      --capacity 1Gi                         \
      --namespace minio              \
      --storageClassName local-storage        \
```

## Context

can't create a tenant 

## Your Environment

* Version used (`minio-operator`):
Image: minio/k8s-operator:v3.0.29
* Environment name and version (e.g. kubernetes v1.17.2):   
Client Version: v1.19.0
Server Version: v1.19.4

* Server type and version: minio/minio:RELEASE.2020-11-19T23-48-16Z
* Operating System and version (`uname -a`):Linux nilegfx 5.4.0-53-generic #59-Ubuntu SMP Wed Oct 21 09:38:44 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

* Link to your deployment file: there is no deployment, I am following the operator pattern
## update
I think the problem doesn't happen when using minikube, it happened in the production cluster

production cluster uses is created with rancher. 

in minikube it created the following secrets: 
```
xx-console-secret   Opaque                                5      26m
xx-console-tls      Opaque                                2      26m
xx-creds-secret     Opaque                                2      26m
xx-tls              Opaque                                2      26m
operator-webhook-secret     Opaque                        3      26m
```

in production it only create: 
```
xx-console-secret   Opaque                                5      26m
xx-creds-secret     Opaque                                2      26m
operator-webhook-secret     Opaque                        3      26m
```

any hint on how to debug this? 

## update 2
after some time, I think waiting for certificates timed-out and the operator continued to create the pods, however, as the certificates (secrets) wasn't created, so the pod initiation failed due to mission the tls secrets

```
kubectl get csr                             
NAME                                      AGE   SIGNERNAME                     REQUESTOR                                      CONDITION
xx-console-minio-xx-csr   32m   kubernetes.io/legacy-unknown   system:serviceaccount:default:minio-operator   Approved
xx-minio-xx-csr           52m   kubernetes.io/legacy-unknown   system:serviceaccount:default:minio-operator   Approved
```

**Comment by Nilegfx** [comment]
[this answer](https://github.com/minio/operator/issues/395#issuecomment-748650296) solved my certificate creation problem, however, I still think the docs for the operator is outdated.

**Comment by harshavardhana** [comment]
You should read the docs for the relevant tag here @Nilegfx https://github.com/minio/operator/tree/v3.0.29 - master branch has diverged and is moving to v0.4.0

**Comment by ustiugov** [comment]
The README needs to be updated: at least 2 service creation arguments are obsolete: `--name` is required and `--storage-class` is a new name for the old agreement.  hence, the correct command is:
```
kubectl minio tenant create --name minio-tenant-1 --servers 1 --volumes 16 --capacity 100Mi --storage-class local-storage
```

**Comment by ravindk89** [comment]
@ustiugov as noted, the command you specified is valid for the v0.3.29 tag, and you can find an older readme [here](https://github.com/minio/operator/tree/v3.0.29). Since we intend to update to 0.4.0 imminently, I do not think we will be updating that tag readme. 

As far as concerns about changing API and syntax - the documentation can only ever cover what the product's state *is*, which in this case is a change in API and syntax. I'm going to add a note to the top of the docs warning users that the master branch is the master branch - which is to say, it reflects the latest bleeding-edge version of the plugin. Users on a specific tagged release must see the documentation for that tag.

**Comment by annonch** [comment]
The documentation is outdated for the v0.3.29 tag as well...

**Comment by ravindk89** [comment]
@annonch just for my own tracking, what issue did you run into for the 3.0.29 tag? 

As far as 4.0.0, you can see the pending issues [here](https://github.com/minio/operator/issues?q=is%3Aopen+is%3Aissue+label%3Arelease-4.0)

**Comment by annonch** [comment]
I was able to use the 3.0.29 tag to install and create a tenant. The Console image is outdated so I reran with -o tenant.yaml instead of directly applying, and replace the image with 5.0.2. The old version was not a problem in and of itself, the --cert-dir passed in to that version caused the container to crash on startup. 5.0.2 starts correctly however I am unable to use it due to certificate errors. The Chart repo for minio met my needs much better :) 

cheers, will keep the operator in mind for the future

**Comment by harshavardhana** [comment]
Closing v4.0.0 released
