### ISSUE TITLE
Undocumented `externalCertSecret` usage

### ISSUE THREAD

**Issue by birdcolour** [minio/operator#430]
The console setting `spec.console.externalCertSecret` (analagous to the [tenant setting](https://github.com/minio/operator/blob/v3.0.29/docs/tls.md#pass-certificate-secret-to-tenant)) is not included in the console [documentation](https://github.com/minio/operator/blob/v3.0.29/docs/console.md#console-fields), nor the raw yaml that this doc refers to - only in the [custom cert](https://github.com/minio/operator/blob/v3.0.29/examples/tenant-with-custom-cert-encryption-disabled.yaml#L165) [examples](https://github.com/minio/operator/blob/113323b8cfee1c63e48c0505f6c90a67852662ae/examples/tenant-with-custom-cert-encryption-enabled.yaml#L232).

I noticed this problem while setting up a console deployment, but a quick check indicates the same documentation issue applies to KES as well.

As a small gotcha, it should also be noted that both of these `externalCertSecret` usages are not yaml arrays, like the tenant version, but yaml dictionaries.

**Comment by ravindk89** [comment]
@birdcolour we're working on re-doing the docs for operator, with some special attention to the CRD at this time. 

You can actually find an example of this on the newly generated https://github.com/minio/operator/blob/master/docs/crd.adoc . Please note that this new CRD reflects the state of the operator *in master*. For older versions of the Operator, you'll need to examine the CRD directly. 

As far as the gotcha, I believe this is intentional. This field effectively enables SNI for the MinIO Console, so it can respond appropriately to requests for, say, `console.minio-tenant-1.example.net` . If it looks like our users consistently tend to set up multiple hostnames for their console deployments, I think we'll have to revisit at that point.

**Comment by nitisht** [comment]
Closing this for now.

**Comment by ravindk89** [comment]
https://docs.min.io/minio/k8s/reference/minio-operator-reference.html#minio-console-service <- early preview of the docs in question, which includes a reference to the specified item. Hope that helps @birdcolour
