### ISSUE TITLE
Minio Operator v4.0.0 Waiting for operator cert "operator-tls" is forbidden

### ISSUE THREAD

**Issue by djfoley01** [minio/operator#520]
## Expected Behavior

Expect the operator to provision the operator-tls certificate and create the operator-tls secret.

## Current Behavior

Operator is failing to provision the secret. 
I0305 17:33:35.988986       1 csr.go:242] Certificate successfully fetched, creating secret with Private key and Certificate
E0305 17:33:35.991518       1 operator.go:129] Unexpected error during the creation of the secret/operator-tls: secrets "operator-tls" is forbidden: cannot set blockOwnerDeletion in this case because cannot find RESTMapping for APIVersion minio.min.io/v2 Kind Operator: no matches for kind "Operator" in version "minio.min.io/v2"
I0305 17:33:35.991541       1 main-controller.go:601] Waiting for the operator certificates to be issued secrets "operator-tls" is forbidden: cannot set blockOwnerDeletion in this case because cannot find RESTMapping for APIVersion minio.min.io/v2 Kind Operator: no matches for kind "Operator" in version "minio.min.io/v2"
I0305 17:33:45.996013       1 main-controller.go:598] operator TLS secret not found%!(EXTRA string=secrets "operator-tls" not found)

I tried to create a tenant anyways and I got this:
E0305 17:38:52.350630       1 main-controller.go:720] error syncing 'minio/test': secrets "operator-tls" not found

## Steps to Reproduce (for bugs)

1. oc minio init --namespace minio --namespace-to-watch minio
2. oc logs minio-operator-66c95df5d8-nggqp
3.
4.

## Context

The old operator 3.0.29 appears to function as intended. I'd like to upgrade to use 4.0.0 however I cannot get the operator to function.

## Your Environment

* Version used (`minio-operator`): v4.0.0
* Environment name and version (e.g. kubernetes v1.17.2): v1.19.0+e405995
* Server type and version: Openshift 4.6.17
* Operating System and version (`uname -a`): CoreOS
* Link to your deployment file:

**Comment by harshavardhana** [comment]
Fixed by #508

**Comment by h-graf** [comment]
I get this error in Version 4.1.0 too. It seems like that the temporary fix for this from this commit: 

https://github.com/minio/operator/commit/c1d330746b9e86717921b099911649cd14362944#diff-4fbe8b303fe610f592f607eb0b4fad84bb934d89568cd384e2428b8886817fd4

got overwritten by this commit: https://github.com/minio/operator/commit/5c08b0d45bb595a36d126420fdb1885bed479831#diff-4fbe8b303fe610f592f607eb0b4fad84bb934d89568cd384e2428b8886817fd4

So it seems the error is back since there is still no operator kind (at least I couldn't find a CRD file).
