### ISSUE TITLE
asset cleanup when tenant is deleted

### ISSUE THREAD

**Issue by travisghansen** [minio/operator#589]
## Expected Behavior

Any assets associated with the tenant (created by the operator) are removed when the tenant is deleted.

## Current Behavior

Currently (at least) secrets and csr object stay floating around. I'm not sure what happens with pvcs yet.

## Steps to Reproduce (for bugs)

1. Create a tenant
2. Delete a tenant
3. Observe orphan secrets and csr objects etc
4.

## Your Environment

* Version used (`minio-operator`): 4.0.5
* Environment name and version (e.g. kubernetes v1.17.2): 1.19
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your deployment file:

**Comment by Nilegfx** [comment]
I was just about to report the same issue.

**Comment by dvaldivia** [comment]
We leave the secrets and the PVCs on purpose by design, the CSRs get cleaned automatically later on. 

Our reasoning is that you don't want to delete a 1PB tenant by accident(deleting the tenant or the CRD), if you really want all that data gone you should clear the PVCs which is standard kubernetes behavior.

As for the secret, it's needed to recover the tenant in case you want to recover. I don't think we'll add cascade delete for these two resources.
