### ISSUE TITLE
Upgrade path from 2.0.9 `MinioInstance` -> 4.x `Tenant`

### ISSUE THREAD

**Issue by mjnagel** [minio/operator#662]
Currently we are using the 2.0.9 operator and `MinioInstance` CRD.

We are looking for an upgrade path to the 4.x operator and the newer `Tenant` CRD without losing any data.

It does not appear that the operator handles this upgrade currently, but if I'm mistaken I'd love to see how this works. If there's at least a manual path in place that we could follow that would help us, but ideally this would all be done automatically by the operator.

If anyone has any info on whether this is already an automatic feature, a manual process, or whether this should be a feature request that would be great.

**Comment by nitisht** [comment]
While there is a conversion webhook that is well tested with operator release `3.X` to `4.X` upgrade, there is no well tested path for `2.X` to `4.X`. 

I'd recommend you migrate the setup manually. You could take the data backup and then create a fresh setup with latest operator and move the data back.

**Comment by iceman2077** [comment]
@nitisht do you have any notes how to upgrade from v3 to v4?

**Comment by dvaldivia** [comment]
@iceman2077 the conversion webhook is bundled with the operator v4, when it starts it updates the CRD so that the k8s can convert between tenants v3 and v4 seamlessly, in theory you can have your tenants v3 upgrade to v4, or a v4 tenant converted to v3 just fine, there's some new features that we've not been including in v3 such as tenant domains.
