### ISSUE TITLE
Stuck at the message "MinIO is not ready" when create a multiple-pools tenant.

### ISSUE THREAD

**Issue by pjamenaja** [minio/operator#735]
Hi,

I believe that the MinIO Operator (version I'm using is v4.1.3) is having the issue if a tenant has multiple pools. Not sure if this relates to https://github.com/minio/operator/issues/732 or not.

Thanks,
Seub

## Expected Behavior
It should be able to start a multiple-pools tenant like it is able to do for a single pool tenant.

## Current Behavior
Stuck a the errors like "E0719 16:38:17.092372       1 main-controller.go:754] error syncing 'minio-applog-a/minio-applog-a': MinIO is not ready"

## Steps to Reproduce (for bugs)
1. Just try to create a tenant with single pool then everything runs as expect and so smooth.
2. Try to create a tenant with 2 pools as the tenant.yam attached (I renamed it to .txt extention)
[tenant.yaml.txt](https://github.com/minio/operator/files/6845406/tenant.yaml.txt) and you will see that the Operator struggles with a lot of "MinIO is not ready" messages.

## Context
N/A

## Regression
N/A

## Your Environment
K8S RKE (Rancher Kubernetes Engine)

**Comment by toabi** [comment]
Ha, after wasting hours and hours today, I also found out that this is indeed the case!

And the problem lies here: https://github.com/minio/operator/blob/0f43eee7fd7ac6ead1695d97ffcfffe776b11e64/pkg/controller/cluster/main-controller.go#L954

When creating a multi-pool tenant, the status doesn't include both pools, so it does a health-check which fails.

And it doesn't throw very useful error messages.

**Comment by toabi** [comment]
Hm. That line in the controller was changed… might need a second try if they accidentally fixed that issue.
