### ISSUE TITLE
scope probes to pool in tenant spec

### ISSUE THREAD

**Issue by AdheipSingh** [minio/operator#945]
- IMHO i feel probes ( readiness and liveliness ) can be scoped in pool spec. As of now it is scoped in the tenant spec.
https://github.com/minio/operator/blob/f844ce202f333141742b4467a773d2af82bd11eb/pkg/apis/minio.min.io/v2/types.go#L486

- probes are k8s native key/values and not minio operator specific.

- or any specific reason for scoping it too tenant :) 

Thanks

**Comment by harshavardhana** [comment]
Liveness and Readiness do not respond specific for pools. Any pool not being available means an entire tenant not being available.

The concept of pool is meant for expansion alone, they do not exist as any independent entities for clients to poll and make sense of.

So that is why it's scoped at tenant level.

**Comment by AdheipSingh** [comment]
got it thanks
